// Shared decorative emoji fallback used until real photos come from the
// media API. Matches on keywords found in an animal's common name and
// falls back to a paw print when nothing matches.

const EMOJI_KEYWORDS = [
  ['lion', '🦁'],
  ['tiger', '🐯'],
  ['leopard', '🐆'],
  ['cheetah', '🐆'],
  ['jaguar', '🐆'],
  ['elephant', '🐘'],
  ['giraffe', '🦒'],
  ['zebra', '🦓'],
  ['rhino', '🦏'],
  ['hippo', '🦛'],
  ['bear', '🐻'],
  ['panda', '🐼'],
  ['koala', '🐨'],
  ['kangaroo', '🦘'],
  ['monkey', '🐒'],
  ['gorilla', '🦍'],
  ['chimp', '🦍'],
  ['orangutan', '🦧'],
  ['sloth', '🦥'],
  ['wolf', '🐺'],
  ['fox', '🦊'],
  ['raccoon', '🦝'],
  ['otter', '🦦'],
  ['beaver', '🦫'],
  ['deer', '🦌'],
  ['moose', '🦌'],
  ['bison', '🦬'],
  ['buffalo', '🦬'],
  ['camel', '🐫'],
  ['llama', '🦙'],
  ['alpaca', '🦙'],
  ['horse', '🐴'],
  ['pig', '🐗'],
  ['boar', '🐗'],
  ['goat', '🐐'],
  ['sheep', '🐑'],
  ['cow', '🐄'],
  ['bat', '🦇'],
  ['rabbit', '🐇'],
  ['hare', '🐇'],
  ['squirrel', '🐿️'],
  ['mouse', '🐭'],
  ['rat', '🐀'],
  ['hedgehog', '🦔'],
  ['dog', '🐕'],
  ['cat', '🐈'],
  ['penguin', '🐧'],
  ['owl', '🦉'],
  ['eagle', '🦅'],
  ['hawk', '🦅'],
  ['falcon', '🦅'],
  ['parrot', '🦜'],
  ['flamingo', '🦩'],
  ['peacock', '🦚'],
  ['swan', '🦢'],
  ['duck', '🦆'],
  ['crane', '🦩'],
  ['chicken', '🐔'],
  ['turkey', '🦃'],
  ['crocodile', '🐊'],
  ['alligator', '🐊'],
  ['snake', '🐍'],
  ['lizard', '🦎'],
  ['iguana', '🦎'],
  ['gecko', '🦎'],
  ['turtle', '🐢'],
  ['tortoise', '🐢'],
  ['frog', '🐸'],
  ['toad', '🐸'],
  ['shark', '🦈'],
  ['whale', '🐋'],
  ['dolphin', '🐬'],
  ['seal', '🦭'],
  ['walrus', '🦭'],
  ['octopus', '🐙'],
  ['squid', '🦑'],
  ['crab', '🦀'],
  ['lobster', '🦞'],
  ['shrimp', '🦐'],
  ['jellyfish', '🪼'],
  ['starfish', '⭐'],
  ['fish', '🐟'],
  ['spider', '🕷️'],
  ['scorpion', '🦂'],
  ['ant', '🐜'],
  ['bee', '🐝'],
  ['butterfly', '🦋'],
  ['dragonfly', '🐞'],
  ['snail', '🐌'],
  ['worm', '🪱'],
]

export function getAnimalEmoji(commonName) {
  if (!commonName) return '🐾'

  const normalized = commonName.toLowerCase()

  const match = EMOJI_KEYWORDS.find(([keyword]) =>
    normalized.includes(keyword)
  )

  return match ? match[1] : '🐾'
}